// defined by webpack
declare const APP_VERSION: string;
declare const CREATE_STEPS: string;
declare const UPDATE_ENROLLMENT_HISTORY_STEPS: string;
declare const UPDATE_COURSE_LIST_STEPS: string;
declare const DELETE_STUDENT_STEPS: string;
declare const DELETE_ADVISOR_STEPS: string;
declare const ASSIGN_TO_CURRENT_ADVISOR_STEPS: string;
declare const DEACTIVATE_STEPS: string;
declare const RESET_COURSE_PLAN_PERMISSIONS_STEPS: string;
declare const RESET_STUDENT_FOLDER_PERMISSIONS_STEPS: string;
declare const RESET_ADVISOR_FOLDER_PERMISSIONS_STEPS: string;
