// defined by webpack
declare const APP_VERSION: string;
declare const CREATE_STEPS: string;
declare const UPDATE_HISTORY_STEPS: string;
declare const UPDATE_COURSES_STEPS: string;
declare const DELETE_STEPS: string;
declare const REASSIGN_STEPS: string;
declare const INACTIVE_STEPS: string;
declare const RESET_PERMISSIONS_STEPS: string;
